---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricsmultiplexer
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: metricsmultiplexer
  template:
    metadata:
      labels:
        app: metricsmultiplexer
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: metricsmultiplexer
      containers:
      - name: multiplexer
        image: {{ $.Values.image }}
        {{ if $.Values.resources }}
        resources:
{{ toYaml $.Values.resources | indent 10 }}
        {{- end }}
        command:
        - "sh"
        - "/multiplexer-entrypoint.sh"
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /multiplexer-entrypoint.sh
          subPath: entrypoint.sh
        - name: config
          mountPath: /multiplexer-nginx.conf
          subPath: multiplexer-nginx.conf
        - name: config
          mountPath: /reloader.sh
          subPath: reloader.sh
      volumes:
      - name: config
        configMap:
          name: metricsmultiplexer
          defaultMode: 0544
