---
apiVersion: v1
kind: Service
metadata:
  name: metricsmultiplexer
  labels:
    app: metricsmultiplexer
spec:
  selector:
    app: metricsmultiplexer
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
